 # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: job1
  steps:
  - script: echo Hello, world, changed!
    displayName: 'Run a one-line script'

- job: job2
  dependsOn: job1
  steps:
  - script: echo Hello 2, world, changed!
    displayName: 'Run a one-line script'

- job: job3
  dependsOn: job2
  steps:
  - script: echo Hello 3, world, changed!
    displayName: 'Run a one-line script'

- job: job4
  dependsOn: 
    - job1
    - job2
  steps:
  - script: echo Hello 4, world, changed!
    displayName: 'Run a one-line script'

