trigger:
- master
  
pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: FirstJob
        steps:
          - bash: echo Build First Job $(Testvariable)
          - bash: echo Build Number is $(Build.BuildNumber)
          - bash: echo Build ID is $(Build.BuildId)
          - bash: echo Branch name is $(Build.SourceBranchName)
          - bash: echo $(Build.SourcesDirectory)
          - bash: echo $(Build.ArtifactStagingDirectory)
          - bash: echo $(System.DefaultWorkingDirectory)
          - bash: ls -R $(System.DefaultWorkingDirectory)
          - bash: java -version
          - bash: node --version
          - bash: python --version
          - bash: mvn -version
          - bash: ls -R $(Build.ArtifactStagingDirectory)
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: |
                **/*.tf
                **/*.yml
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - bash: ls -R $(Build.ArtifactStagingDirectory)
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

      # - job: SecondJob
      #   steps:
      #     - bash: echo Build Second Job $(Testvariable)

  # - stage: DevDeploy
  #   variables:
  #     environment: Dev
  #   dependsOn: Build
  #   jobs:
  #     - job: DevDeploy
  #       steps:
  #         - bash: echo $(environment)Deploy job
  
  # - stage: QADeploy
  #   variables:
  #     environment: QA
  #   dependsOn: 
  #   - Build
  #   jobs:
  #     - job: QADeploy
  #       steps:
  #         - bash: echo $(environment)Deploy job
  
  # - stage: ProdDeploy
  #   variables:
  #     environment: Prod
  #   dependsOn:
  #   - QADeploy
  #   - DevDeploy
  #   jobs:
  #     - job: ProdDeploy
  #       steps:
  #         - bash: echo $(environment)Deploy job


